services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: python manage.py runserver 0.0.0.0:8000
  db:
    image: postgres:latest
    volumes:
      - .:/app/data/db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5433"
